### ISSUE TITLE
Tag release 2.0.0?

### ISSUE THREAD

**Issue by spookylukey** [thetalecrafter/elm-intl#7]
Would it be good to tag current master as 2.0.0? I think this may be a necessary step to get the latest version and docs to appear on http://elm-directory.herokuapp.com/package/vanwagonet/elm-intl/

**Comment by vanwagonet** [comment]
Sure. I think adding a new tag is fine.

**Comment by spookylukey** [comment]
OK. I've done that now, thanks.
